name: wled_cli
description: CLI for controlling WLED instances
version: 0.0.1
repository: https://github.com/dector/wled-cli-dart

environment:
  sdk: ^3.2.5

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
